games:
  arène1:
    players: []
    enable: true
    world: br
    spawnpoint:
      - 100.5,64,200.5
      - 102.0,64,203.0
      - 105.3,64,205.7
      # ... jusqu'à 100 coordonnées


  arène2:
    players: []
    enable: true
    world: br
    spawnpoint:
      - 100.5,64,200.5
      - 102.0,64,203.0
      - 105.3,64,205.7
      # ... jusqu'à 100 coordonnées