games:
  "Arène 1":
    players: []
    enable: true
    world: br
    spawnpoint:
      - 100.5,64,200.5,0,0
      - 102.0,64,203.0,0,0
      - 105.3,64,205.7,0,0
      # ... jusqu'à 100 coordonnées


  "Arène 2":
    players: []
    enable: true
    world: br
    spawnpoint:
      - 100.5,64,200.5,0,0
      - 102.0,64,203.0,0,0
      - 105.3,64,205.7,0,0
      # ... jusqu'à 100 coordonnées
