name: BattleRoyale
version: '1.0-SNAPSHOT'
main: fr.ixsou.battleroyale.Main
api-version: '1.21'
authors: [ Ixsou_mod ]
commands:
  battleroyale:
    description: Rejoindre ou quitter une arène Battle Royale.
  battleroyaleforcestart:
    description: Forcer le démarrage d’une arène.
    permission: group.admin
  battleroyalereload:
    description: Reload la config du Battle Royale.
    permission: group.admin
  setspawnpoint:
    description: Définit un point de spawn pour une arène
    usage: /setspawnpoint <arena>
    permission: group.admin
